-- SQL statements which are executed at application startup if hibernate.hbm2ddl.auto is 'create' or 'create-drop'
insert into osoba (id, imie, nazwisko) values (1, 'Jaś', 'Fasola');
insert into osoba (id, imie, nazwisko) values (2, 'Bonawentura', 'Nowak');
insert into osoba (id, imie, nazwisko) values (3, 'Delfina', 'Muc');
insert into osoba (id, imie, nazwisko) values (4, 'Emeryk', 'Robak');
insert into osoba (id, imie, nazwisko) values (5, 'Filipina', 'Gazda');
insert into osoba (id, imie, nazwisko) values (6, 'Gracja', 'Roztocka');
insert into osoba (id, imie, nazwisko) values (7, 'Hildegarda', 'von Stolzenberg');
insert into osoba (id, imie, nazwisko) values (8, 'Idzi', 'Brzęczyszczykiewicz');
insert into osoba (id, imie, nazwisko) values (9, 'Wierzchosława', 'Złotopolska-Aleksandrowicz');
insert into osoba (id, imie, nazwisko) values (10, 'Kunegunda', 'Sobieska');
insert into osoba (id, imie, nazwisko) values (11, 'Leontyna', 'Dzierżyńska');
insert into osoba (id, imie, nazwisko) values (12, 'Leontyna', 'Niesiołowska');
insert into student (grupadziekanska, indeks, id) values ('GID101', 's1234', 1);
insert into student (grupadziekanska, indeks, id) values ('GID101', 's1235', 2);
insert into student (grupadziekanska, indeks, id) values ('GID101', 's1236', 3);
insert into student (grupadziekanska, indeks, id) values ('GID101', 's1232', 4);
insert into student (grupadziekanska, indeks, id) values ('GID101', 's1134', 5);
insert into student (grupadziekanska, indeks, id) values ('GID101', 's4234', 6);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's5234', 7);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's6234', 8);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's7234', 9);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's8234', 10);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's9234', 11);
insert into student (grupadziekanska, indeks, id) values ('GID201', 's1874', 12);
